### PR TITLE
fix: Added routes and Modified AuthController

### LINKED ISSUE #6: Fix and Modify Routes and AuthController

### PR DESCRIPTION
**Pull request by adish-ian**
Resolves #6

### CODE REVIEW

File: routes/api.php [hunk 1]
```diff
@@ -8,6 +8,9 @@
 Route::post('/register', [AuthController::class, 'register']);
 Route::post('/login', [AuthController::class, 'login']);
 
+// Fetch authenticated user details
+Route::middleware('auth:sanctum')->get('/user', [AuthController::class, 'getUser']);
```
Comment (ADSI-kevincaliboso) [inline routes/api.php]: Put this inside the group for protected routes. To remove another sanctum protected group unless you will need this for *later.

**Review by ADSI-kevincaliboso — CHANGES_REQUESTED** [review]
After change, ship it!
